### ISSUE TITLE
Replace rubocop:disable in code with Rubocop configuration

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/gcloud-ruby#408]
I consider the `rubocop:disable` statements an anti-pattern that adds unwelcome noise to the codebase. We should embrace Rubocop's flexibility and configure it (sparingly, of course) to support our own notion of good style.

**Comment by blowmage** [comment]
The change I'd make to `.rubocop.yml` is:

```yaml
Metrics/AbcSize:
  Max: 20
Metrics/MethodLength:
  Max: 15
```
